apiVersion: v1
kind: Service
metadata:
  name: k8s-hello-genserver
spec:
  type: NodePort
  ports:
  - protocol: TCP
    name: http
    port: 4000
    targetPort: 4000
  selector:
      app: k8s-hello-genserver